controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_controller:
      type: joint_state_controller/JointStateController

    xarm6_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

xarm6_traj_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    interface_name: position
