controller_names:
  - fake_xarm6_traj_controller
  - fake_xarm_gripper_controller

fake_xarm6_traj_controller:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6

fake_xarm_gripper_controller:
  joints:
    - drive_joint
