controller_names:
  - L_xarm6_traj_controller
  - L_xarm_gripper
  - R_xarm6_traj_controller
  - R_xarm_gripper

L_xarm6_traj_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - L_joint1
    - L_joint2
    - L_joint3
    - L_joint4
    - L_joint5
    - L_joint6

L_xarm_gripper:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints:
    - L_drive_joint

R_xarm6_traj_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - R_joint1
    - R_joint2
    - R_joint3
    - R_joint4
    - R_joint5
    - R_joint6

R_xarm_gripper:
  action_ns: gripper_action
  type: GripperCommand
  default: true
  joints:
    - R_drive_joint
