default_joint_limits:
  joint1:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -360.0
    max_position: !degrees 360.0
  joint2:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -118.0
    max_position: !degrees 120.0
  joint3:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -225.0
    max_position: !degrees 11.0
  joint4:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -97.0
    max_position: !degrees 180.0
  joint5:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -360.0
    max_position: !degrees 360.0

joint_limits:
  joint1:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -180.0
    max_position: !degrees 180.0
  joint2:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -118.0
    max_position: !degrees 120.0
  joint3:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -180.0
    max_position: !degrees 11.0
  joint4:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -97.0
    max_position: !degrees 180.0
  joint5:
    has_acceleration_limits: false
    has_effort_limits: false
    has_velocity_limits: true
    has_position_limits: true
    max_acceleration: 0
    max_effort: 0
    max_velocity: 2.14
    min_position: !degrees -180.0
    max_position: !degrees 180.0

