controller_names:
  - fake_xarm5_traj_controller
  - fake_xarm_gripper_controller

fake_xarm5_traj_controller:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5

fake_xarm_gripper_controller:
  joints:
    - drive_joint
